# Generated by Django 3.0.6 on 2020-06-20 09:22

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=90)),
                ('city', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('facebook', models.URLField(blank=True, null=True, unique=True)),
                ('twitter', models.URLField(blank=True, null=True, unique=True)),
                ('linkedin', models.URLField(blank=True, null=True, unique=True)),
                ('youtube', models.URLField(blank=True, null=True, unique=True)),
                ('website', models.URLField(blank=True, null=True, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('is_verified', models.BooleanField(default=False)),
                ('dp', models.ImageField(default='placeholders/user/avatar-1577909.svg', upload_to=accounts.models.Owner.owner_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('dp', models.ImageField(blank=True, default='placeholders/user/avatar-1577909.svg', null=True, upload_to=accounts.models.Profile.profile_directory_path)),
            ],
        ),
    ]
