# Generated by Django 3.0.6 on 2020-06-20 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('rank', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125)),
                ('slug', models.SlugField()),
                ('property_type', models.CharField(choices=[('flat', 'Flat'), ('apartment', 'Apartment'), ('condominium', 'Condo'), ('single', 'Single'), ('self', 'Self'), ('bedsitter', 'Bedsitter')], max_length=50)),
                ('rooms', models.PositiveSmallIntegerField()),
                ('is_verified', models.BooleanField(default=False)),
                ('is_sponsored', models.BooleanField(default=False)),
                ('is_furnished', models.BooleanField()),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('photo_1', models.ImageField(upload_to='listing')),
                ('photo_2', models.ImageField(upload_to='listing')),
                ('photo_3', models.ImageField(upload_to='listing')),
                ('photo_4', models.ImageField(upload_to='listing')),
                ('photo_5', models.ImageField(upload_to='listing')),
                ('amenities', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='property.Amenities')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Owner')),
                ('rating', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='property.Rating')),
            ],
            options={
                'verbose_name_plural': 'Properties',
            },
        ),
    ]
