# Generated by Django 3.0.6 on 2020-06-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenities',
            options={'verbose_name_plural': 'Amenities'},
        ),
        migrations.AddField(
            model_name='property',
            name='price',
            field=models.PositiveIntegerField(default=3299),
        ),
    ]
