# Generated by Django 3.0.6 on 2020-06-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_auto_20200620_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='transaction',
            field=models.CharField(choices=[('sale', 'FOR SALE'), ('rent', 'FOR RENT')], default='sale', max_length=10),
        ),
    ]
